### ISSUE TITLE
关于项目名字

### ISSUE THREAD

**Issue by ourai** [yutingzhao1991/github-blogs-weekly#10]
个人认为叫「issue-blogs」更为贴切。如果是「github-blogs」的话，利用 Github Pages 的也应该算。

**Comment by yutingzhao1991** [comment]
嗯，确实。不过我之前是有计划把 Github Pages 中的博客更新也算进来的 :P 。可以去自动抓取 github pages 里面更新的 md 文件，所以就先不改了吧，以后找时间把这个做了就变成名副其实的 github-blogs了。有没有谁可以帮忙开发这一块的 ：D
