### ISSUE TITLE
关于这一条：“作者为本人的且字数大于200的会每加入推送列表中”

### ISSUE THREAD

**Issue by cssmagic** [yutingzhao1991/github-blogs-weekly#16]
如果 repo 是在 org 下的话，则 “作者为本人” 总是无法实现。

我在 `config.json` 中发现了 `publicRepos` 这个字段，是用来标记这种情况的吗？

**Comment by yutingzhao1991** [comment]
嗯 是的 publicRepos 就是用来标记这种情况的。这些限制主要是为了过滤一些噪音，但是我认为是可以去掉 “作者为本人”这个限制，通过把字数大于200这个限制调整大一点没准会好一些。

**Comment by cssmagic** [comment]
好的，明白了。我感觉现有的 “双保险” 规则 OK。

另外，建议把 `publicRepos` 字段改名为 `orgRepos`。在 GitHub 上，public/private 有专门的含义。
