### ISSUE TITLE
github-blogs 优化意见收集

### ISSUE THREAD

**Issue by yutingzhao1991** [yutingzhao1991/github-blogs-weekly#18]
也不知道什么时候开始国内的前端届开始流行在Github的Issues中写博客，写博客的体验是好了，但是读者却纠结了。star获取不到更新，watch又太吵，浏览不方便。所以做了这么一个小工具，到现在也有60+的人在watch了，期望能够通过这个工具能够增强技术交流的氛围造福广告码农，及时汲取大大们的成果。

但是到现在发现一些不是很满意的地方，期望能够收集一些意见进行下一步的优化和重构。我个人想到的大概有如下一些点：

1. 更新的频率是否需要调整，使得能够更及时的获取更新（每天？甚至是每篇更新）
2. 关于blog的list的维护是否还需要自动化？是不是直接人工维护会更好？或者说自动化抓取只是作为一个小工具，最终还是由人工维护？
3. 是否需要支持部分不是通过issue而是直接通过github pages发布的blog？如何去自动抓取？
4. 每次更新的issue格式优化？展示一下文章概览？
5. 更新抓取的规则是否需要调整？去掉“本人创建”的限制？加大字数的限制？
6. 用于更新推送的repo和项目的repo是否需要分离，进一步减少本项目更新带来的干扰？
7. 是否需要支持通过邮箱或者rss等订阅方式？

打扰各位了，不知道对上面这个优化点持什么意见。如果有什么好的意见欢迎提出来，也欢迎大家贡献代码。

**Comment by cssmagic** [comment]
感谢作者！我通过这个项目发现了不少好文章 :smile:。 我挑几个问题谈一下自己的看法：

> 更新的频率是否需要调整，使得能够更及时的获取更新（每天？甚至是每篇更新）

我自己感觉每周推送一次挺好。

> 每次更新的issue格式优化？展示一下文章概览？

“概览” 可以有！

> 更新抓取的规则是否需要调整？去掉“本人创建”的限制？加大字数的限制？

在 #16 听了作者的解释之后，感觉现有规则 OK。

> 用于更新推送的repo和项目的repo是否需要分离，进一步减少本项目更新带来的干扰？

感觉是需要的。宜早不宜迟。

> 是否需要支持通过邮箱或者rss等订阅方式？

对我来说不是必需。另外，用户通过 [合理配置 GitHub 消息提醒](https://github.com/cssmagic/blog/issues/49) 可以实现邮箱订阅的效果。

**Comment by yutingzhao1991** [comment]
@cssmagic 多谢你的意见，宜早不宜迟！那现在就做。博客收集的程序已经迁移到 [github-blogs-collector](https://github.com/yutingzhao1991/github-blogs-collector) 这个repo以后只作为weekly的更新。这样方便不打扰到关注这个项目的人的情况下能够快速迭代更新github-blogs-collector。

**Comment by bit-ranger** [comment]
抓取github pages的blog没那么简单，我就喜欢在博客内乱插各种liquid标签，而不是正正经经地写markdown，估计这样的人不会少。

**Comment by yutingzhao1991** [comment]
@dubuyuye 抓取github pages的blog确实比较麻烦，但是也是可行的。我的想法是首先通过判断是否有gh-pages这个分支以及是否包含blog类似的特征来找到这一类的bloglist（这个哪怕人工维护也行）。然后就是抓取_posts这个文件夹下的md文件了（顺便问一下_posts这个文件夹应该是固定的吧，Jekyll能够修改么），然后通过路径就能推算出blog得地址，其实也不是特别复杂。

**Comment by bit-ranger** [comment]
@yutingzhao1991
_posts目录是可配置的，但是问题不大。
问题是，md里面可能存在liquid标签，不能直接抓过来用。

**Comment by yutingzhao1991** [comment]
@dubuyuye md文件里面存着liquid标签无所谓了，我们也不用去抓取内容，只要发现有md文件更新就可以，最终还是跳转到博客的页面。

**Comment by yutingzhao1991** [comment]
@all 因为获取更新和文章抓取的repo已经分离，所以关闭该issue。如果有问题和意见可以到 [github-blogs-collector](https://github.com/yutingzhao1991/github-blogs-collector) 上面建issue。另外新增了一个每日更新的repo [github-blogs-daily](https://github.com/yutingzhao1991/github-blogs-daily/search?q=&state=open&type=Issues&utf8=%E2%9C%93) 想要获取更及时推送的朋友可以关注这个项目。
